/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.forms;

/**
 *
 * @author rafael
 */
public class FrameAbout extends javax.swing.JFrame {

    /**
     * Creates new form FrameAbout
     */
    public FrameAbout() {
        initComponents();
        setLocationRelativeTo(null);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        painelLogoSobre = new javax.swing.JPanel();
        labelLogoSobre = new javax.swing.JLabel();
        labelDesenvolvedor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setType(java.awt.Window.Type.POPUP);

        painelPrincipal.setLayout(new java.awt.GridLayout(2, 1));

        painelLogoSobre.setLayout(new java.awt.GridLayout(1, 1));

        labelLogoSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/LogoSobre.png"))); // NOI18N
        painelLogoSobre.add(labelLogoSobre);

        painelPrincipal.add(painelLogoSobre);

        labelDesenvolvedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDesenvolvedor.setText("Desenvolvido por Rafael Barbiero");
        painelPrincipal.add(labelDesenvolvedor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelDesenvolvedor;
    private javax.swing.JLabel labelLogoSobre;
    private javax.swing.JPanel painelLogoSobre;
    private javax.swing.JPanel painelPrincipal;
    // End of variables declaration//GEN-END:variables
}
